server:
  port: 8081
spring:
  application:
    name: details
  datasource:
    username: 'unforgettabledew'
    password: '27092100'
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/details
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true